name: fake_news_detection
channels:
  - anaconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - altair=5.4.1
  - annotated-types=0.7.0
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=24.2.0
  - aws-c-auth=0.7.0
  - aws-c-cal=0.6.0
  - aws-c-common=0.8.23
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.11
  - aws-c-io=0.13.28
  - aws-c-mqtt=0.8.14
  - aws-c-s3=0.3.13
  - aws-c-sdkutils=0.1.11
  - aws-checksums=0.1.16
  - aws-crt-cpp=0.20.3
  - aws-sdk-cpp=1.10.57
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.zoneinfo=0.2.1
  - beautifulsoup4=4.12.3
  - bleach=4.1.0
  - blinker=1.8.2
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cachetools=5.5.0
  - catalogue=2.0.10
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - click=8.1.7
  - cloudpathlib=0.20.0
  - colorama=0.4.6
  - comm=0.2.1
  - confection=0.1.4
  - contourpy=1.0.5
  - cycler=0.11.0
  - cymem=2.0.8
  - cython-blis=0.7.10
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - fonttools=4.51.0
  - freetype=2.13.3
  - gensim=4.3.3
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glib=2.84.0
  - glib-tools=2.84.0
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=70.1
  - idna=3.10
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - intel-openmp=2024.2.1
  - ipykernel=6.29.5
  - ipython=8.12.2
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.10
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - langcodes=3.4.1
  - language-data=1.2.0
  - lerc=4.0.0
  - libabseil=20230125.3
  - libarrow=12.0.1
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcurl=8.1.2
  - libdeflate=1.22
  - libevent=2.1.12
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.84.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.56.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - liblapack=3.9.0
  - libogg=1.3.5
  - libpng=1.6.47
  - libprotobuf=4.23.3
  - libsodium=1.0.18
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libthrift=0.18.1
  - libtiff=4.5.0
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - marisa-trie=1.2.0
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.2
  - mistune=2.0.4
  - mkl=2024.2.2
  - msys2-conda-epoch=20160418
  - murmurhash=1.0.10
  - narwhals=1.13.3
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - nltk=3.9.1
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - numexpr=2.7.3
  - numpy=1.24.4
  - openssl=3.5.0
  - orc=1.9.0
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - ply=3.11
  - pooch=1.8.2
  - preshed=3.0.9
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=4.23.3
  - psutil=5.9.0
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pyarrow=12.0.1
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pydeck=0.8.0
  - pygments=2.18.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.8
  - pytz=2024.1
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qt-main=5.15.8
  - qtconsole=5.6.0
  - qtpy=2.4.1
  - re2=2023.03.02
  - referencing=0.30.2
  - regex=2024.7.24
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.10.6
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=75.1.0
  - shellingham=1.5.4
  - sip=6.7.12
  - six=1.16.0
  - smart-open=7.0.5
  - smart_open=7.0.5
  - smmap=5.0.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - spacy=3.7.6
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sqlite=3.45.3
  - srsly=2.4.8
  - stack_data=0.2.0
  - streamlit=1.41.1
  - tbb=2021.13.0
  - tenacity=9.0.0
  - terminado=0.17.1
  - textblob=0.15.3
  - thinc=8.2.5
  - threadpoolctl=3.5.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.12.5
  - typer-slim=0.12.5
  - typer-slim-standard=0.12.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - tzlocal=5.2
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wasabi=1.1.2
  - watchdog=4.0.1
  - wcwidth=0.2.5
  - weasel=0.4.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.10
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.16.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - en-core-web-sm==3.7.1
